/// Flutter icons IconHome
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconHome
///      fonts:
///       - asset: fonts/IconHome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconHome {
  IconHome._();

  static const _kFontFam = 'IconHome';

  static const IconData membershipcard = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData three_stripes = const IconData(0xe801, fontFamily: _kFontFam);
}
