name: shuguoyinxiang
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  flutter_swiper: ^1.1.6
  xml: ^3.5.0
  http: ^0.12.0+2
  cached_network_image: ^2.0.0-rc
  shared_preferences: ^0.5.4+5
  image_picker: ^0.6.2+1
  url_launcher: ^5.5.0
  sqflite: ^1.2.0
  intro_slider: ^2.2.8
  intl: ^0.16.1
  barcode_scan: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "img/sgyx_1024.png"
  image_path_android: "img/logo_launcher_sgyx.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/logo_sgyx.webp
    - img/email_logo.webp
    - img/password_logo.webp
    - img/indonesia.png
    - img/promo.webp
    - img/beef.webp
    - img/beef_5.webp
    - img/logo_red_sgyx.webp
    - img/akun_user.webp
    - img/icon_history.webp
    - img/barcode.png
    - img/qr_code.png
    - img/bg_product.webp
    - img/promo_example.webp
    - img/outlet_revisi.webp
    - img/promo_revisi.webp
    - img/product_revisi.webp
    - img/gambar_revisi.webp
    - img/Catering Service.webp
    - img/border_revisi.webp
    - img/logo_shu_guo_white.webp
    - img/catering_service.webp
    - img/product_bg.jpg
    - img/home.webp
    - img/slider_1.webp
    - img/slider_2.webp
    - img/opening_page_1.webp
    - img/opening_page_3.webp
    - img/opening_page_2.webp
    - img/opening_page_4.webp
    - img/golden_frame.webp
    - img/akun_user_white.webp
    - img/home_test.webp
    - img/product_revisi2.webp
    - img/promotion_revisi2.webp
    - img/cook_book.webp
    - img/outlet_revisi2.webp
    - img/catering_service_revisi2.webp
    - img/Login.webp
    - img/img_background_product.webp
    - img/sgyx_1024.png
    - img/JudulCookbook.webp
    - img/bg_home.webp
    - img/bg_products_menu.webp
    - img/about_loyalty.webp
    - img/close_button.webp
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: font/OpenSans-Regular.ttf
    - family: OpenSansBold
      fonts:
        - asset: font/OpenSans-Bold.ttf
    - family:  CustomIcon
      fonts:
        - asset: font/CustomIcon.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: font/MyFlutterApp.ttf
    - family:  IconHome
      fonts:
        - asset: font/IconHome.ttf
    - family:  IconIdCard
      fonts:
        - asset: font/IconIdCard.ttf
    - family: IconAddPoint
      fonts:
        - asset: font/IconAddPoint.ttf
    - family: Kano
      fonts:
        - asset: font/Kano.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
